version: '3.7'

services:
  infra:
    container_name: terraform-infra
    image: terraform-infra
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TERRAFORM_VERSION: ${TERRAFORM_VERSION}
    volumes:
      - .:/project
