version: '3.7'

services:
  infra:
    container_name: toolbox_infra
    image: infra
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TERRAFORM_VERSION: ${TERRAFORM_VERSION}
        GCLOUD_VERSION: ${GCLOUD_VERSION}
    volumes:
      - .:/project
    env_file: 
      - gcp.env
      - aws.env
    entrypoint: /project/entrypoint.sh